name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.2.0,<0.3.0
  - jupyterlite-xeus-python >=0.9.2,<0.10.0
  - pip:
    - ./urllib3-2.1.0-py3-none-any.whl
    - ./frozenlist-1.4.0-py3-none-any.whl
    - ./multidict-4.7.6-py3-none-any.whl
    - ./aiohttp-3.9.1-py3-none-any.whl
    - ./openai-1.3.8-py3-none-any.whl
    - ssl
    - httpx
